dist: trusty
language: rust
addons:
  apt:
    packages: [libpcap0.8, libpcap0.8-dev]
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --all --verbose
  - cargo test --all --verbose
